// <auto-generated />
using System;
using FitMaster.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitMaster.Infrastructure.Migrations
{
    [DbContext(typeof(FitMasterDbContext))]
    [Migration("20260910190012_AddInjuryMuscleExclusions")]
    partial class AddInjuryMuscleExclusions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitMaster.Domain.Entities.ActivityLogging.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<long>("PerformedById")
                        .HasColumnType("bigint")
                        .HasColumnName("performed_by");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.Equipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.Exercise", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("difficulty_level");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.ExerciseEquipment", b =>
                {
                    b.Property<byte[]>("ExerciseId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("exercise_id");

                    b.Property<long>("EquipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.HasKey("ExerciseId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("exercise_equipment", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.ExerciseMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("exercise_id");

                    b.Property<byte[]>("MediaAssetId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sex")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ViewAngle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("view_angle");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MediaAssetId");

                    b.ToTable("exercise_media", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.ExerciseMuscle", b =>
                {
                    b.Property<byte[]>("ExerciseId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("exercise_id");

                    b.Property<long>("MuscleId")
                        .HasColumnType("bigint")
                        .HasColumnName("muscle_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExerciseId", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.ToTable("exercise_muscles", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.ExerciseTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AudioCueUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("audio_cue_url");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("exercise_translations", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.MediaAsset", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("AttributionText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("attribution_text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("license_type");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.MovementPattern", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("movement_patterns", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.Muscle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("body_region");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("muscles", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Identity.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AdminRoleAssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("admin_role_assigned_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit")
                        .HasColumnName("is_activated");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profile_picture");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Members.MemberProfile", b =>
                {
                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allergies");

                    b.Property<string>("FitnessLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("HasDiabetes")
                        .HasColumnType("bit")
                        .HasColumnName("has_diabetes");

                    b.Property<bool>("HasHeartConditions")
                        .HasColumnType("bit")
                        .HasColumnName("has_heart_conditions");

                    b.Property<bool>("HasHypertension")
                        .HasColumnType("bit")
                        .HasColumnName("has_hypertension");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Injuries")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("injuries");

                    b.Property<string>("SplitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("split_type");

                    b.Property<string>("TrainingStyle")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("training_style");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("MemberId");

                    b.ToTable("member_profiles", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Memberships.Membership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Debt")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PackageId");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Memberships.Package", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Memberships.Revenue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<long>("MembershipId")
                        .HasColumnType("bigint")
                        .HasColumnName("membership_id");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipId");

                    b.ToTable("revenues", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Notifications.NotificationUserState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    b.Property<bool>("Read")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("NotificationId", "UserId")
                        .IsUnique();

                    b.ToTable("notification_user_state", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionFood", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("CarbsGrams")
                        .HasColumnType("int")
                        .HasColumnName("carbs_grams");

                    b.Property<int>("FatGrams")
                        .HasColumnType("int")
                        .HasColumnName("fat_grams");

                    b.Property<long>("MealId")
                        .HasColumnType("bigint")
                        .HasColumnName("meal_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProteinGrams")
                        .HasColumnType("int")
                        .HasColumnName("protein_grams");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("nutrition_foods", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionMeal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MealTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("meal_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("NutritionPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    b.Property<string>("PrepTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prep_time");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("int")
                        .HasColumnName("total_calories");

                    b.HasKey("Id");

                    b.HasIndex("NutritionPlanId");

                    b.ToTable("nutrition_meals", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CarbsGrams")
                        .HasColumnType("int")
                        .HasColumnName("carbs_grams");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("int")
                        .HasColumnName("daily_calories");

                    b.Property<int>("FatGrams")
                        .HasColumnType("int")
                        .HasColumnName("fat_grams");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<int>("ProteinGrams")
                        .HasColumnType("int")
                        .HasColumnName("protein_grams");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("nutrition_plans", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionRecipeStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MealId")
                        .HasColumnType("bigint")
                        .HasColumnName("meal_id");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("step_order");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("nutrition_recipe_steps", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.InjuryMuscleExclusion", b =>
                {
                    b.Property<string>("InjuryType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("injury_type");

                    b.Property<long>("MuscleId")
                        .HasColumnType("bigint")
                        .HasColumnName("muscle_id");

                    b.HasKey("InjuryType", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.ToTable("injury_muscle_exclusions", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.WorkoutDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int")
                        .HasColumnName("day_number");

                    b.Property<string>("MuscleGroupLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("muscle_group_label");

                    b.Property<long>("WorkoutPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("workout_plan_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("workout_days", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.WorkoutExercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<byte[]>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("exercise_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("RepsMax")
                        .HasColumnType("int")
                        .HasColumnName("reps_max");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<long>("WorkoutDayId")
                        .HasColumnType("bigint")
                        .HasColumnName("workout_day_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("workout_exercises", (string)null);
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.WorkoutPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SplitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("split_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("workout_plans", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<long>("RolesId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("exercise_patterns", b =>
                {
                    b.Property<byte[]>("exercise_id")
                        .HasColumnType("binary(16)");

                    b.Property<long>("pattern_id")
                        .HasColumnType("bigint");

                    b.HasKey("exercise_id", "pattern_id");

                    b.HasIndex("pattern_id");

                    b.ToTable("exercise_patterns");
                });

            modelBuilder.Entity("exercise_tags", b =>
                {
                    b.Property<byte[]>("exercise_id")
                        .HasColumnType("binary(16)");

                    b.Property<long>("tag_id")
                        .HasColumnType("bigint");

                    b.HasKey("exercise_id", "tag_id");

                    b.HasIndex("tag_id");

                    b.ToTable("exercise_tags");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.ActivityLogging.ActivityLog", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Identity.User", "PerformedBy")
                        .WithMany("ActivityLogsPerformed")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.ExerciseEquipment", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Exercises.Equipment", "Equipment")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.ExerciseMedia", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany("Media")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Exercises.MediaAsset", "MediaAsset")
                        .WithMany("ExerciseMedia")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.ExerciseMuscle", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Exercises.Muscle", "Muscle")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.ExerciseTranslation", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany("Translations")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Identity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Members.MemberProfile", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Identity.User", "Member")
                        .WithOne("MemberProfile")
                        .HasForeignKey("FitMaster.Domain.Entities.Members.MemberProfile", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Memberships.Membership", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Identity.User", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Memberships.Package", "Package")
                        .WithMany("Memberships")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Memberships.Revenue", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Identity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Identity.User", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Memberships.Membership", "Membership")
                        .WithMany("Revenues")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Notifications.NotificationUserState", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Notifications.Notification", "Notification")
                        .WithMany("UserStates")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Identity.User", "User")
                        .WithMany("NotificationStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionFood", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Nutrition.NutritionMeal", "Meal")
                        .WithMany("Foods")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionMeal", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Nutrition.NutritionPlan", "NutritionPlan")
                        .WithMany("Meals")
                        .HasForeignKey("NutritionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutritionPlan");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionPlan", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Identity.User", "Member")
                        .WithMany("NutritionPlans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionRecipeStep", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Nutrition.NutritionMeal", "Meal")
                        .WithMany("RecipeSteps")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.InjuryMuscleExclusion", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Exercises.Muscle", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.WorkoutDay", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Workouts.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.WorkoutExercise", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Workouts.WorkoutDay", "WorkoutDay")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.WorkoutPlan", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Identity.User", "Member")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("exercise_patterns", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("exercise_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Exercises.MovementPattern", null)
                        .WithMany()
                        .HasForeignKey("pattern_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("exercise_tags", b =>
                {
                    b.HasOne("FitMaster.Domain.Entities.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("exercise_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitMaster.Domain.Entities.Exercises.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.Equipment", b =>
                {
                    b.Navigation("ExerciseEquipments");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.Exercise", b =>
                {
                    b.Navigation("ExerciseEquipments");

                    b.Navigation("ExerciseMuscles");

                    b.Navigation("Media");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.MediaAsset", b =>
                {
                    b.Navigation("ExerciseMedia");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Exercises.Muscle", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("ActivityLogsPerformed");

                    b.Navigation("MemberProfile");

                    b.Navigation("Memberships");

                    b.Navigation("NotificationStates");

                    b.Navigation("NutritionPlans");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Memberships.Membership", b =>
                {
                    b.Navigation("Revenues");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Memberships.Package", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Navigation("UserStates");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionMeal", b =>
                {
                    b.Navigation("Foods");

                    b.Navigation("RecipeSteps");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Nutrition.NutritionPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.WorkoutDay", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("FitMaster.Domain.Entities.Workouts.WorkoutPlan", b =>
                {
                    b.Navigation("WorkoutDays");
                });
#pragma warning restore 612, 618
        }
    }
}
